### ISSUE TITLE
Data files

### ISSUE THREAD

**Issue by mdavezac** [basp-group/purify#11]
@olebole. These files are mostly provided to run examples. As such they are not necessary per se, but still useful. We could add a switch to disable their installation if that's more convenient.

**Comment by olebole** [comment]
Original request was:

> Hi Mayeul,
> 
> most size of the purify source is taken by the data files. Do they have
> a use outside of the build/test procedure? I am asking since I am
> curious of whether they should be packaged as a binary package for Purify.
> 
> Best regards
> 
> Ole

For me, having it there is fine. Especially since they are used for build time tests.

**Comment by mdavezac** [comment]
Okay, good.
