### ISSUE TITLE
Please consider assigning version numbers

### ISSUE THREAD

**Issue by olebole** [basp-group/purify#2]
Hi,

we are thinking of [packaging purify for the Debian distribution](https://bugs.debian.org/830126). For this, it would help much, if you could assign a version number to the current release. This makes it easier for the user to reference to a specific release. And since sopt is unchanged since a year, the current status can be taken as quite stable

Thank you very much,

best regards

Ole

**Comment by jasonmcewen** [comment]
Hi Ole,

Thanks for your interest in sopt and purify.  

Although the public versions of these repositories haven't changed much in the last year or so, there have been a very large number of developments on a private version of the repository.  In fact, the codes have been completely redesigned and rewritten.  The private developments will be pushed to these public repositories once they are complete, probably in the next month or so.

I would therefore recommend packaging a sopt/purify distribution once the new updates are pushed.  We will also be sure to assign a version number to the next release.

Best,
Jason

**Comment by olebole** [comment]
Hi Jason,

thank you very much for your response  ( FYI @gijzelaerr). We'll wait before uploading to Debian.
However, it would be nice to have access to some pre-releases so that we can start packaging them.
Also, experiences show that usually some bugs can be identified during the packaging process, which probably should go into the final release.
And I thought that github would be a perfect place to smoothly follow the development? 
Maybe you could merge the changes before you release a new version? Just a thought...

Best regards

Ole

**Comment by jasonmcewen** [comment]
Hi Ole,

Let's take this discussion offline.  Can you please email me about this (at jason.mcewen@ucl.ac.uk) and let's discuss further.

Best,
Jason

**Comment by jasonmcewen** [comment]
Hi Ole, we've now assigned version numbers.
